services:
  server:
    image: afxdp_iteration:latest
    build: .
    ports:
      - "9000:9000/udp"
    cap_add:
      - NET_ADMIN
      - SYS_ADMIN
      - IPC_LOCK
    ulimits:
      memlock: -1
    security_opt:
      - seccomp=unconfined
    command: ./build/${VERSION:?set VERSION=v1_blocking_st|v2_blocking_mt|...}/server ${PORT:-9000}
